import type { CertLayout } from "./types";

/**
 * Default layout that mirrors the VIFM Classic .pptx — triple navy border,
 * italic title, attendee name with underline, course title, awarded-on line,
 * signature block bottom-left, double-ring institutional seal bottom-center.
 *
 * Units: x/y/length/diameter are percentages of the canvas. Font sizes are
 * pixels at the canvas's intrinsic 1190 × 842 px (A4 landscape at 100 dpi).
 */
export const DEFAULT_LAYOUT: CertLayout = {
  pageWidth: 297,
  pageHeight: 210,
  background: "#FFFFFF",
  elements: [
    // --- Triple navy border ---
    {
      id: "border-outer",
      type: "rect",
      label: "Outer border",
      x: 1.6,
      y: 1.6,
      width: 96.8,
      height: 96.8,
      borderColor: "#134BA1",
      borderWidth: 3,
      locked: true,
    },
    {
      id: "border-mid",
      type: "rect",
      label: "Middle border",
      x: 2.6,
      y: 2.6,
      width: 94.8,
      height: 94.8,
      borderColor: "#134BA1",
      borderWidth: 1.5,
      locked: true,
    },
    {
      id: "border-inner",
      type: "rect",
      label: "Inner border",
      x: 3.4,
      y: 3.4,
      width: 93.2,
      height: 93.2,
      borderColor: "#134BA1",
      borderWidth: 1,
      locked: true,
    },

    // --- Top-left brand ---
    {
      id: "brand-mark",
      type: "text",
      label: "Brand wordmark",
      x: 6,
      y: 7,
      text: "VIFM",
      fontSize: 56,
      fontFamily: "sans",
      fontWeight: 700,
      fontStyle: "normal",
      color: "#134BA1",
      align: "left",
    },
    {
      id: "brand-tagline",
      type: "text",
      label: "Brand tagline",
      x: 6,
      y: 13,
      text: "Virginia Institute of Finance and Management",
      fontSize: 14,
      fontFamily: "sans",
      fontWeight: 400,
      fontStyle: "normal",
      color: "#787878",
      align: "left",
      letterSpacing: 1,
    },

    // --- Top-right cert number ---
    {
      id: "cert-number",
      type: "text",
      label: "Certificate number",
      x: 94,
      y: 7,
      text: "Certificate No. {{CODE}}",
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 400,
      fontStyle: "normal",
      color: "#787878",
      align: "right",
    },

    // --- Italic title ---
    {
      id: "title",
      type: "text",
      label: "Title",
      x: 50,
      y: 26,
      text: "Certificate of Completion",
      fontSize: 76,
      fontFamily: "serif",
      fontWeight: 400,
      fontStyle: "italic",
      color: "#134BA1",
      align: "center",
    },

    // --- Caption + attendee name + underline ---
    {
      id: "caption-1",
      type: "text",
      label: "Caption — acknowledges",
      x: 50,
      y: 42,
      text: "THIS ACKNOWLEDGES THAT",
      fontSize: 18,
      fontFamily: "sans",
      fontWeight: 400,
      fontStyle: "normal",
      color: "#4B5563",
      align: "center",
      letterSpacing: 3,
    },
    {
      id: "attendee-name",
      type: "text",
      label: "Recipient name",
      x: 50,
      y: 50,
      text: "{{ATTENDEE_NAME}}",
      fontSize: 60,
      fontFamily: "serif",
      fontWeight: 700,
      fontStyle: "normal",
      color: "#134BA1",
      align: "center",
    },
    {
      id: "name-underline",
      type: "line",
      label: "Underline",
      x: 30,
      y: 58,
      length: 40,
      color: "#134BA1",
      thickness: 1,
    },

    // --- Course caption + title ---
    {
      id: "caption-2",
      type: "text",
      label: "Caption — completed",
      x: 50,
      y: 62,
      text: "HAS SUCCESSFULLY COMPLETED",
      fontSize: 18,
      fontFamily: "sans",
      fontWeight: 400,
      fontStyle: "normal",
      color: "#4B5563",
      align: "center",
      letterSpacing: 3,
    },
    {
      id: "course-title",
      type: "text",
      label: "Course title",
      x: 50,
      y: 70,
      text: "{{COURSE_TITLE}}",
      fontSize: 38,
      fontFamily: "serif",
      fontWeight: 700,
      fontStyle: "normal",
      color: "#134BA1",
      align: "center",
      width: 80,
    },

    // --- Awarded date ---
    {
      id: "awarded-date",
      type: "text",
      label: "Awarded on",
      x: 50,
      y: 80,
      text: "Awarded on {{DATE_RANGE}} for {{CLIENT_NAME}}",
      fontSize: 18,
      fontFamily: "sans",
      fontWeight: 400,
      fontStyle: "normal",
      color: "#4B5563",
      align: "center",
    },

    // --- Signature bottom-left ---
    {
      id: "sig-line",
      type: "line",
      label: "Signature line",
      x: 8,
      y: 88,
      length: 18,
      color: "#787878",
      thickness: 1,
    },
    {
      id: "sig-name",
      type: "text",
      label: "Signatory name",
      x: 8,
      y: 90,
      text: "AIMAN S. SADEQ",
      fontSize: 16,
      fontFamily: "sans",
      fontWeight: 700,
      fontStyle: "normal",
      color: "#134BA1",
      align: "left",
    },
    {
      id: "sig-title",
      type: "text",
      label: "Signatory title",
      x: 8,
      y: 93,
      text: "MANAGING DIRECTOR",
      fontSize: 12,
      fontFamily: "sans",
      fontWeight: 400,
      fontStyle: "normal",
      color: "#787878",
      align: "left",
      letterSpacing: 2,
    },

    // --- Seal bottom-center ---
    {
      id: "seal-outer",
      type: "circle",
      label: "Seal outer ring",
      x: 50,
      y: 91,
      diameter: 9,
      borderColor: "#134BA1",
      borderWidth: 2,
      locked: false,
    },
    {
      id: "seal-inner",
      type: "circle",
      label: "Seal inner ring",
      x: 50,
      y: 91,
      diameter: 7.5,
      borderColor: "#134BA1",
      borderWidth: 1,
      locked: false,
    },
    {
      id: "seal-line-1",
      type: "text",
      label: "Seal — line 1",
      x: 50,
      y: 88.5,
      text: "VIRGINIA INSTITUTE",
      fontSize: 9,
      fontFamily: "sans",
      fontWeight: 700,
      fontStyle: "normal",
      color: "#134BA1",
      align: "center",
    },
    {
      id: "seal-line-2",
      type: "text",
      label: "Seal — line 2",
      x: 50,
      y: 90.5,
      text: "OF FINANCE",
      fontSize: 9,
      fontFamily: "sans",
      fontWeight: 700,
      fontStyle: "normal",
      color: "#134BA1",
      align: "center",
    },
    {
      id: "seal-year",
      type: "text",
      label: "Seal — year",
      x: 50,
      y: 92.5,
      text: "2010",
      fontSize: 18,
      fontFamily: "serif",
      fontWeight: 700,
      fontStyle: "normal",
      color: "#134BA1",
      align: "center",
    },
    {
      id: "seal-line-3",
      type: "text",
      label: "Seal — line 3",
      x: 50,
      y: 94.5,
      text: "VIRGINIA · USA",
      fontSize: 8,
      fontFamily: "sans",
      fontWeight: 700,
      fontStyle: "normal",
      color: "#134BA1",
      align: "center",
    },
  ],
};
